version: '3.8'

services:
  backend:
    build: .
    container_name: api-libreria
    ports:
      - "3000:3000" 
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - libreria-network

  db:
    image: mysql:8.0
    container_name: mysql-libreria
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: libreria
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - libreria-network

volumes:
  mysql_data:

networks:
  libreria-network:
    driver: bridge
